### ISSUE TITLE
Optimize plugin configuration

### ISSUE THREAD

**Issue by yakovlevkll** [kazupon/vue-i18n#1018]
First, thanks for the great plugin, it saves me a lot of time!

I have some ideas about optimization of the code needed for plugin configuration.

After plugin is added via `vue add` command there are 4 places where new settings come up

- `main.ts`
- `.env`
- `vue.config.ts`
- `i18n.ts`

So the questions are:
1. Is there any way to merge settings from `vue.config.ts` and `i18n.ts`?
2. Does the function `loadLocaleMessages()` need to be exactly in `i18n.ts`? Maybe it can be bundeled into main package?

Best regards,
Kll

**Comment by kazupon** [comment]
Thank you for your feedback!

> 1. Is there any way to merge settings from `vue.config.ts` and `i18n.ts`?

This is where the configuration information for vue-cli is placed.
We don't plan to set the locale options for vue-i18n in `vue.config.ts`.

> 2\. Does the function `loadLocaleMessages()` need to be exactly in `i18n.ts`? Maybe it can be bundeled into main package?


The vue-cli generated i18n.ts is scaholded to incorporate vue-i18n into applications created with vue-cli.

We also plan to update vue-cli-plugin-i18n in the future.
Since vue-cli also migrate i18n.ts with its migration feature, it's not recommended to change the code in the file.

If you change the contents of the i18n.ts file, it means that vue-cli will not be able to migrate vue-i18n in the future.
