### ISSUE TITLE
How to configure locales like a.b and a.b.c

### ISSUE THREAD

**Issue by l2m2** [kazupon/vue-i18n#1144]
My expected usage is
```js
$t("a.b")
$t("a.b.c")
```
How to configure locales like this?
```json
{
  "a": { "b": "Hello a.b" },
  "a": { "b.c": "Hello a.b.c" } ???????
}
```

**Comment by exoego** [comment]
JavaScript objects can not have duplicate keys: your example contains duplicate `a`.

```json
{
  "a.b":   "Hello a.b",
  "a.b.c": "Hello a.b.c"
}
```
will work, as long as all keys are flat: https://jsfiddle.net/0yhqpf75/2/

However, if a key is an object, the object should not contain `.` in keys.
Because, if the nested key contain `.`,  the behavior could be confusing: https://jsfiddle.net/0yhqpf75/3/

If you would like to have some nested locale objects to shorten key prefix, `.` should not be used in keys: https://jsfiddle.net/0yhqpf75/4/

**Comment by exoego** [comment]
Closing since this seems not an issue of vue-i18n but a how-to-use question.
Please understand [the issue repording guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines).

**Comment by l2m2** [comment]
Answer: https://jsfiddle.net/l2m2lq/ukc817d6/4/
