### ISSUE TITLE
cannot translation with using i18n custom block locale messages

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-i18n#169]
### vue & vue-i18n version
vue-i18n 7.0.0

### Reproduction repo
https://github.com/Korri/vue-i18n-issue-demo

### Related issues
https://github.com/kazupon/vue-i18n-loader/issues/4

**Comment by Korri** [comment]
I updated my example repo to version 7.0.1 and I now get the new warning message `Cannot parse locale messages via custom blocks.`

I did some debugging and the Json is parsed properly. I don't know what the issue is.

I created a branch where you can test it: https://github.com/Korri/vue-i18n-issue-demo/tree/v-7
Same as before just run
```bash
npm install
npm run unit
```

**Comment by kazupon** [comment]
fixed in v7.0.2
please check it!
https://github.com/kazupon/vue-i18n/releases/tag/v7.0.2

**Comment by Korri** [comment]
Works now!
