### ISSUE TITLE
Dynamically inserted component doesn't have the $i18n instance injected.

### ISSUE THREAD

**Issue by yesyo** [kazupon/vue-i18n#186]
Please see the fiddle. 
I have no idea if it's a bug or an intended behavior. Thanks.

### vue & vue-i18n version
2.3.0, 7.0.3

### Reproduction Link
http://jsfiddle.net/cxjfzowu/

**Comment by kazupon** [comment]
Thank you for your feedback!

I checked your reproduction link.
Component (this case `Hello`) inserted with `appendChild` DOM API cannot use `$i18n`.
The root Vue instance can not find the hello instance, due to each instance is independent.

You need to create `VueI18n` instance for `Hello` instance, and need to set `i18n` option to it.
