### ISSUE TITLE
Dynamic loading a language object instead of load all  in the begin when i have 10 language. 

### ISSUE THREAD

**Issue by admin00001** [kazupon/vue-i18n#223]
now ，my code is like that：
```
import Vue from 'vue';
import VueI18n from 'vue-i18n';
import en from 'module/user/i18n/en';
import zh from 'module/user/i18n/zh';

Vue.use(VueI18n);

const messages = {
  en: en,
  zh: zh,
  ...
};
let lang = window.localStorage.getItem('lang') || 'en';

export default new VueI18n({
  locale: lang,
  messages
});
```
but and i want to dynamic loading a language objec like this:
```
import Vue from 'vue';
import VueI18n from 'vue-i18n';
//  import en from 'module/user/i18n/en';
// import zh from 'module/user/i18n/zh';

Vue.use(VueI18n);

const messages = {
  en:  () => import('module/user/i18n/en');  // i want to  dynamic loading,but it does not work!!!
  zh:  () => import('module/user/i18n/zh');  
};
...
```

**Comment by matrixise** [comment]
+1

**Comment by kuanhsuh** [comment]
This is the feature you are looknig for.
https://kazupon.github.io/vue-i18n/en/migrations.html#features

**Comment by kuanhsuh** [comment]
I have a question, does it increase your bundle.js by a lot if you only load 1 json file compare to 5 json files. A pretty packed language json is around 3kb? and this will get uglify so does it really matter by loading all at once?

**Comment by smares** [comment]
Loading all possible languages if your user only uses English for example is not sensible. Not only does it increase the bundle size, but the localizations for several languages also have to be kept in memory.

**Comment by rodneyrehm** [comment]
> `en:  () => import('module/user/i18n/en');  // i want to  dynamic loading,but it does not work!!!`

We've solved this by using [webpack's bundle-loader](http://webpack.js.org/loaders/bundle-loader/) (see [webpack Code Splitting](https://webpack.js.org/guides/code-splitting/)) for all languages but the default locale, which is part of the app bundle. In our case supporting a language involves a bit more than just the JSON for vue-18n (e.g. CLDR for messageformat), so having webpack bundle that stuff made the most sense to us.

Once the lazy-loaded JSON is available, we simply add the data to the messages object passed to the vue-i18n constructor and set the locale property.

We visually hide the UI while the JSON is not yet available. While we can't yet show the end result, we can allow vue to create all the components and DOM while we're downloading the language - that way vue "only" has to update a few text nodes… since we already had a "splash screen loading indication" in place, this was not a big deal.

Note that vue-i18n is completely oblivious to any of this. While this approach is not ideal I'm not sure having vue-i18n take care of the lazy-loading is the best course of action.

---

> I have a question, does it increase your bundle.js by a lot if you only load 1 json file compare to 5 json files.

throwing the JSON for German at [Closure Compiler](https://closure-compiler.appspot.com) gives me:

original: 22.44KB
compressed: 18.42KB
gzipped: 6.77KB

we currently support 10 languages with more to be expected and our app is nowhere finished, meaning the JSON files will only grow. So yes, bundling all the translations definitely is a problem.

**Comment by wxsms** [comment]
+1 I NEED THIS THANKS!!

**Comment by kuanhsuh** [comment]
Hi guys, I figure it out.

Here's the code in my vuex.

``` javascript
async setLangNew({commit}, payload){
    if (payload in app.$i18n.messages) {
      commit(types.SET_LANG, payload)
    } else {
      try {
        // const res = await axios.get(`./src/lang/${payload}.json`)
        // const res = await axios.get(`../../src/lang/${payload}.json`)
        const res = await import(`./src/lang/locale/${payload}.json`)
        app.$i18n.setLocaleMessage(payload, res.data)
        commit(types.SET_LANG, payload)
      }
      catch(e) {
        console.log(e)
      }
    }
  }
```

if you want the full demo, you can check out my repo, [vue-i18n sandbox](https://github.com/kuanhsuh/vue-i18n-sandbox)

**Comment by arjanski** [comment]
This is an article that also deals with dynamic loading of languages, maybe similar to @rodneyrehm 's approach? 

http://digital-cult.com/vue-i18n-async-loading-languages/

**Comment by kazupon** [comment]
close, due to exists workaround the below:
https://kazupon.github.io/vue-i18n/en/lazy-loading.html

**Comment by evzpav** [comment]
QWQw

**Comment by LbISS** [comment]
@evzpav It seems that the problem could be in your loadLanguageAsync function and the names of resources objects.

For example, if you have in your loadfunction code
```
export function loadLanguageAsync (lang) {
...
      return import(`@/lang/${lang}`).then(msgs => {
        i18n.setLocaleMessage(lang, **msgs.resources**)
```

then in pt.js and en.js you should have objects with property 'resources'
```
export const en = {
    msg:
        {
            account: 'Account',
            account_description: 'Account description',
       }
}
```

**Comment by evzpav** [comment]
@LbISS Thanks a lot for your time to write me an answer! Stupid mistake from my part. 
Thanks again!
