### ISSUE TITLE
Cannot translate the value of keypath 'message.welcome'. Use the value of keypath as default.

### ISSUE THREAD

**Issue by polikin** [kazupon/vue-i18n#244]
### vue & vue-i18n version
```
"vue": "^2.0.1",
"vue-i18n": "^7.3.2",
```

### Reproduction Link
github: https://github.com/polikin/vuejs-boilerplate

### Steps to reproduce
`main.js`
```
import Vue from 'vue';
import App from './App.vue';
import router from './router/index';
import i18n from './locale/index';

new Vue({
    el: '#app',
    template: '<App/>',
    components: { App },
    router,
    i18n
}).$mount('#app'); //mount the router on the app
```

`locale/index.js`

```
import Vue from 'vue';
import VueI18n from 'vue-i18n'
import messages from './message';

Vue.use(VueI18n)

const i18n = new VueI18n({
  locale: 'en',
  messages
});
```

`locale/message.js`

```
export default [
    {
        en: {
            message: {
                welcome: 'Welcome'
            }
        },
        fr: {
            message: {
                welcome: 'Bonjour'
            }
        }
    }
];

export default i18n;
```
### What is Expected?
`Hello.vue`
`<p>{{ $t("message.welcome") }}</p>` should render 'Welcome'`

### What is actually happening?
I get this error: `vue-i18n.common.js:16 [vue-i18n] Cannot translate the value of keypath 'message.welcome'. Use the value of keypath as default.`

**Comment by Miguel-Herrero** [comment]
Hi @polikin I had this problem until I read [this comment](https://github.com/kazupon/vue-i18n/issues/49#issuecomment-337136653). My problem was that I renamed the messages property (exactly like in the comment). Renaming it made the thing work.

Maybe your problem is related with exporting the translations. I notice that you don't `export default i18n` in your `locale/index.js`and I've different messages file:

```
const messages = {
  en: {
    home: {
      someString: 'Una cadena de texto'
    }
  },
  es: {
    home: {
      someString: 'A string of text'
    }
  }
}

export default messages
```

Hope it helps! :)

**Comment by polikin** [comment]
Thanks, it's working.

**Comment by abhimatta999** [comment]
Hello, I am setting up i18n in same way but getting warnings for the same, but its translating all the words though. Can anyone help me with this.

**Comment by DanielWaltherCode** [comment]
I experienced the same problem and in my case it was caused by referencing variables that were not available at page load. I used a variable I fetched from my API as a translation key and since this was not immediately available I got warning messages (but once the api call went through the string was translated correctly).

Adding a simple v-if to check if the variable was set got rid of the warning message.

**Comment by HassanZeitoun** [comment]
I am using Nuxt js,
I have an i18n.js file inside the config folder, and I was facing this issue
for me, it worked by adding require

```
export default {
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    'en': require ('../locales/en.json'),
    'fr': require ('../locales/fr.json'),
    'ar': require ('../locales/ar.json'),
    'es': require ('../locales/es.json')
  },
}
```
inside nuxt.cnfig.js

```
import i18n from './config/i18n'

export default {
...
modules: [
    '@nuxtjs/i18n',
  ],
  // i18n modlue configuration: https://i18n.nuxtjs.org/setup
  i18n: {
    vueI18nLoader: false,
    locales: [
      {
        code: 'en',
        name: 'English'
      },
      {
        code: 'fr',
        name: 'Français'
      },
      {
        code: 'ar',
        name: 'Arabic'
      },
      {
        code: 'es',
        name: 'Espanol'
      }
    ],
    defaultLocale: 'en',
    vueI18n: i18n   // here is my i18n.js file
  },
  ...
```
