### ISSUE TITLE
[Bug Report] Translation Doesn't Rerender when The Message Change Asynchronously

### ISSUE THREAD

**Issue by jefrydco** [kazupon/vue-i18n#315]
### vue & vue-i18n version
**Vue:** 2.5.16
**Vue I18n:** 7.6.1

### Reproduction Link
https://jsfiddle.net/jefrydco/q5d3cp9a/12/

### Steps to reproduce
Open the link above, take a look in the result box.

### What is Expected?
Whenever the message change, the translation should be re-render.

### What is actually happening?
When the message change, the translation didn't re-render.

**Comment by jefrydco** [comment]
My current workaround is using `then()` block and set the data attribute from there.
```
getData().then(() => {
  this.text = this.$t('keypath')
})
```

**Comment by jefrydco** [comment]
ping @kazupon

**Comment by kazupon** [comment]
sorry, i can not check due to my busy work now.
please wait. 🙇

**Comment by avenla-mvirkkunen** [comment]
@jefrydco The API for setLocaleMessage requires you to specify the locale name:

    setLocaleMessage( locale, message )

Additionally if you add a locale later you need to define it as an empty object first so that Vue reactivity works. So do it like this: https://jsfiddle.net/q5d3cp9a/48/

Alternatively you can use mergeLocaleMessage which uses Vue.set internally: https://jsfiddle.net/q5d3cp9a/49/

**Comment by kazupon** [comment]
close due to answer with @jefrydco 
please see the api [docs](https://kazupon.github.io/vue-i18n/api/#setlocalemessage-locale-message)

**Comment by harolrodriguez** [comment]
> close due to answer with @jefrydco please see the api [docs](https://kazupon.github.io/vue-i18n/api/#setlocalemessage-locale-message)
https://jsfiddle.net/q5d3cp9a/49/

dont work on define it as an empty object
