### ISSUE TITLE
What is $i18n property, and why it might be - "is not defined on the instance"  ?

### ISSUE THREAD

**Issue by olegpopovskiy** [kazupon/vue-i18n#340]
I never had this problem before, and I can't understand where it comes from, can you help me?
I just took starter https://github.com/davidroyer/nuxt-ssr-firebase and nuxt i18n example, both work fine, but once try to merge it, I get this error. I had the same issue when I try to add vue-i18n in my project (a similar problem with nuxt-i18n also).

**Comment by kazupon** [comment]
Colud you provide minimum repro repo please?

**Comment by adi-zz** [comment]
@kazupon, I won't open a new issue because I think I have the same issue like @olegpopovskiy.

Take a look at [this repo](https://github.com/adi-zz/nuxt-vuetify-i18n) (it uses nuxt, vuetify, nuxt-i18n and vue-i18n).

First issue is when you open the homepage (`localhost:3000`). If you open this page via SSR (but not if you browse to homepage inside the SPA), all vuetify's `v-icon` tags don't show the icon, but the text.

Second issue, from homepage, if you click `go to /inspire` button, you will land to `/ENGLISH-inspire` page (as expected), but the console log shows: `[vue-i18n] not exist VueI18n instance in Vue instance`.

Both issues appeared after I upgraded to nuxt-i18n 4.0.0 and vue-i18n 7.8.1, but don't happen in [an older commit](https://github.com/adi-zz/nuxt-vuetify-i18n/commit/be82c847ad58780815d89e1d0464afaf2ee11da2) (nuxt-i18n 2.9.1, vue-i18n 7.6.0).

Thanks

**Comment by shabushabu** [comment]
I'm also getting this warning message after the upgrade to 7.8.1: `[vue-i18n] not exist VueI18n instance in Vue instance`.
I'm using Nuxt 2 and VueI18n is instantiated in a Nuxt Plugin, like so:

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import de from '~/locales/de'
import en from '~/locales/en'

Vue.use(VueI18n)

export default ({app, store}) => {
  app.i18n = new VueI18n({
    locale: store.getters.locale,
    fallbackLocale: 'en',
    silentTranslationWarn: process.env.NODE_ENV === 'production',
    messages: {
      en, de
    }
  })

  if (module.hot) {
    module.hot.accept(['../locales/en', '../locales/de'], () => {
      app.i18n.setLocaleMessage('en', require('../locales/en').default)
      app.i18n.setLocaleMessage('de', require('../locales/de').default)
    })
  }
}
```

**Comment by shabushabu** [comment]
v8.0.0 fixed this issue for me. Cheers!

**Comment by olegpopovskiy** [comment]
> v8.0.0 fixed this issue for me. Cheers!

not for me...
