### ISSUE TITLE
Custom i18n block breaks this.$i18n link

### ISSUE THREAD

**Issue by bovesan** [kazupon/vue-i18n#411]
This might be expected behavior, but I could not understand why my locale changes where suddenly not propagating beyond the local component. 

### What is actually happening?
If a single file component has a custom i18n block, setting `this.$i18n.locale` only affects that component.
### vue & vue-i18n version
2.5.17, 8.0.0

### Example
```
<template>
<div>
<input :placeholder="$t('Search ...')">
            <a href="/language/en" class="dropdown-item" v-on:click.prevent="setLanguage('en')">English</a>
            <a href="/language/no" class="dropdown-item" v-on:click.prevent="setLanguage('no')">Norsk</a>
</div>
</template>
<i18n>
{
  "en": {
  },
  "no": {
    "Search ...": "Søk ..."
  }
}
</i18n>
<script>
 export default {
    methods: {
      setLanguage(language){
        this.$i18n.locale = language;
      }
    }
  }
</script>
```

**Comment by oahccc** [comment]
I encountered the same issue. Is this an intended behavior?

**Comment by progmohamed** [comment]
+1

**Comment by JBtje** [comment]
I believe it is intended behaviour.
Think about this: your website is available in 2-3 languages, but you want users to be able to fill in a form in their own language, w/o having to translate the full website. (e.g. a questionnaire).

Because locale only affects the single component file, you can do this.
You can use something like this to solve the problem. I keep the language stored in a Vuex $store.

    Vue.mixin( {
        computed: {
            locale() {
                return this.$store.state.locale;
            },
        },
        watch:    {
            locale() {
                if( typeof this.$i18n !== 'undefined' ) {
                    this.$i18n.locale = this.locale;
                }
            },
        },
    } );

Using this mixin, you'll update all single component files with the new language, once set in the store. Since it is a mixin, you'll only have to add it to the app.js file once.

**Comment by romain-web** [comment]
any update ?

@kazupon how we can update the root instance of i18n when we use a custom block in the same place ?

**Comment by kazupon** [comment]
This is expected behavior.
If you need to change all locale, as @JBtje mentioned, you can use Vuex and mixin or `this.$root.$i18n.locale`.
