### ISSUE TITLE
Dynamically setting locale messages problem

### ISSUE THREAD

**Issue by gdev219** [kazupon/vue-i18n#446]
### vue & vue-i18n version
ex: 2.1.0, 5.0
3.0.5,8.0.0
### What is Expected?

getting language data from server {lang}.json

### What is actually happening?
my actions in store.js 
```
updatecurrentLocale({ commit }, { instance, locale }) {
  function getLanguage(locale) {
    return instance
      .$http({
        url: 'http://localhost:3000/' + locale + '.json',
        method: 'get',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json'
        }
      })
      .then(response => {
        return response.data;
      });
  }
  const messages = {};
  messages[locale] = getLanguage(locale);
  instance.$i18n.setLocaleMessage(locale, messages);

  commit('update', locale);
}
```

I tried to get locale messages asynchronously  from my local server but it gives me

> Cannot translate the value of keypath <my-message-data>. Use the value of keypath as default.

Dunno what's wrong with this I attempt to solve it with various methods but nothing worked, any helps? thanks for your help in advance.

**Comment by kazupon** [comment]
This is close due to question.
Please make sure to read the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Vue Land](https://vue-land.js.org/),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by rendomnet** [comment]
this is not working
