### ISSUE TITLE
Unable to access numberFormats when i18n tag exists

### ISSUE THREAD

**Issue by zeina-idris** [kazupon/vue-i18n#487]
### Versions
vue 2.5.17
vue-i18n 8.5.0

### Reproduction Link

Demo: https://heuristic-noether-c3f036.netlify.com/
Repository: https://github.com/zeina-idris/vue-i18n-issue

### Example code
```javascript
// main.js
new Vue({
  i18n,
  render: h => h(App)
}).$mount('#app')
```

```javascript
// i18n.js 
Vue.use(VueI18n);

// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: 'en',
  numberFormats: {
    'en-US': {
      currency: {
        style: 'currency', currency: 'USD'
      }
    },
    'de-DE': {
      currency: {
        style: 'currency', currency: 'EUR', currencyDisplay: 'symbol'
      }
    }
  };,
});
export default i18n;
```

```javascript
//with.vue
<template>
  <div class="about">
    <h1>Page with i18n tag</h1>
    <p>{{ $t('hello', 'ja') }}</p>
    <p>{{ $t('hello', 'en') }}</p>
    <!-- Template output: {} -->
    <h2>{{$i18n.numberFormats}}</h2>
  </div>
</template>

<i18n>
{
  "en": {
    "hello": "hello world!"
  },
  "ja": {
    "hello": "こんにちは、世界!"
  }
}
</i18n>
```

```javascript
//without.vue
<template>
  <div class="home">
    <h1> Page without i18n tag </h1>
    <!-- Template output: { "en-US": { "currency": { "style": "currency", "currency": "USD" } }, "de-DE": { "currency": { "style": "currency", "currency": "EUR", "currencyDisplay": "symbol" } } } -->
    <h3>{{$i18n.numberFormats}}</h3>
  </div>
</template>
```

### What is Expected?
To be able to access `$i18n.numberFormats` from vue components that include `<i18n>` tags. since i18n.js is registered globally.

### What is actually happening?
I have two files that both try to access `$i18n.numberFormats` from global i18n file to get the currency.
 When the file has `<i18n>` tag, numberFormats is then an empty object.
When accessing it from the file that doesn't use `<i18n>` tags then I get the object.

**Comment by kazupon** [comment]
Thank you for your reporting.

This is expected behavior.

If you use `<i18n>`, the i18n instance wiil be created to the component.

For this reason, i18n instance have the `numberFormats` such as resouces (`datetimeFormats` `messages`), it's scoped to target component. 

resources other than numberFormsts such as `messages`,` datetimeFormats` are scoped and maintained in the corresponding component.

If you don't use `<i18n>`, is used the root i18n instance.
if you use `<i18n>`, is used the locale i18n intance not root i18n instance.
