### ISSUE TITLE
how to escape html tag when using $t?

### ISSUE THREAD

**Issue by 17leba** [kazupon/vue-i18n#519]
An example:
Locale messages the below:
`const messages = {
  en: {
    message: {
      hello: '{msg} world'
    }
  }
}`

Template the below:
`<div>{{ $t('hello',{msg:'<em>Hello</em>'}) }}</div>`

Result is:
![image](https://user-images.githubusercontent.com/3077512/52624707-48326d00-2eea-11e9-90e2-1097b9813127.png)

How to escape html tag when render?

**Comment by kazupon** [comment]
In template, You need to use HTML entities.
See details https://github.com/vuejs/vue/issues/7860

Genelally, Dynamically localization arbitrary HTML on your website can be very dangerous because it can easily lead to XSS vulnerabilities. 
https://kazupon.github.io/vue-i18n/guide/formatting.html#html-formatting

I recommended that use component interpolation.
https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage
