### ISSUE TITLE
Linked message with Pluralization

### ISSUE THREAD

**Issue by mrcasablr** [kazupon/vue-i18n#521]
I'm using Vue 2.6.6 and 8.8.1 of vue-i18n. There seems to be a bug when plurals are used inside of linked messages and parameters

Here is the jsfiddle -
https://jsfiddle.net/4ufbypz3/1/

The following code works for plural -
```
  {{ $i18n.tc("tropical_fruits",2,{flavor: taste})}}<br/>
```
which prints "mangoes tastes sweet"

while this code for singular fails -
```
{{ $i18n.tc("tropical_fruits",1,{flavor: taste})}}<br/>
```
which prints only "mango"

I would like to use plurals inside linked message and parameters as this simplifies the language files.

I'm not also sure if using the syntax properly

**Comment by lukaVarga** [comment]
Same thing happening for me. Interesting enough, for a custom pluralization, only the singular form works with the parameters and the plural form fails. For English, only the singular form works.

By 'works' I mean that the linked message has both parts. When it doesn't work, the linked message has only the pluralizable part

**Comment by exoego** [comment]
This happens because how `$tc` works, especially a `choice` numer given to `$tc` is NOT propagated to linked key.
https://github.com/kazupon/vue-i18n/blob/ccf29f88d343e9baf2e6a5a9c04ad992c4f5906d/src/index.js#L443

Let's illustrate how it works.

case of 1:
`$i18n.tc("tropical_fruits",1,{flavor: taste})}` 
is translated to `fetchChoice(t('tropical_fruits', {flavor: taste}), 1)`
which is translated to`fetchChoice('mango | mango tastes sweet', 1))`
which is translated to `mango`

case of 2:
`$i18n.tc("tropical_fruits",2,{flavor: taste})}` 
is translated to `fetchChoice(t('tropical_fruits', {flavor: taste}), 2)`
which is translated to `fetchChoice('mango | mango tastes sweet', 2))`
which is translated to `mango tastes sweet`

You can write like https://jsfiddle.net/ufj2pLb5/ for your use case.

**Comment by exoego** [comment]
Linked message with pluralization may be useful, but not possible right now, if my above understanding is correct.
I think it is very difficult to propagate a choice number to linked key message.
Specially, in terms of compatibility, it can be a breaking change if linked key message contains `|` like this case.

IMHO, it should be performed using parameter injection (`{fruit}`) like https://jsfiddle.net/ufj2pLb5/ 
instead of linked key message.

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!

**Comment by zhouxianjun** [comment]
@kazupon Can this support be migrated to v8?
because v9 don't supports vue2
