### ISSUE TITLE
Vue i18n is only working in dev system not on production

### ISSUE THREAD

**Issue by Stefjoe** [kazupon/vue-i18n#663]
Hello,
i implemented the i18n module, after i run npm run build, i get no errors, but a warning, i changed the function loadLocaleMessages() from:

`function loadLocaleMessages() to var loadLocaleMessages = function`, because of a build warning of ESLINT func-style. Now i get no warning and it is working in DEV, only in DEV

But in production it i s still not working, i get this error in console:

`Uncaught TypeError: Cannot read property 'VUE_APP_I18N_LOCALE' of undefined`

What do i have to do? Do i have to upload the json files, seperated from generated code?

Rgds
Stefan

**Comment by kazupon** [comment]
Hi!

>Uncaught TypeError: Cannot read property 'VUE_APP_I18N_LOCALE' of undefined

It seem vue-cli-plugin i18n error for me. 🤔

**Comment by Stefjoe** [comment]
This is my i18n.js

```
import Vue from 'vue';
import VueI18n from 'vue-i18n';

Vue.use(VueI18n);

var  loadLocaleMessages = function () {
  const locales = require.context('./locales', true, /[A-Za-z0-9-_,\s]+\.json$/i);
  const messages = {};
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-_]+)\./i);
    if (matched && matched.length > 1) {
      const locale = matched[1];
      messages[locale] = locales(key);
    }
  });
  return messages;
};

export default new VueI18n({
  locale: process.env.VUE_APP_I18N_LOCALE || 'de',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
  messages: loadLocaleMessages()
});
```

in main.js
`import i18n from './i18n';`

in src/locales i have added my de.json and en.json

**Comment by Stefjoe** [comment]
Hello,
can somebody help me?

Rgds

**Comment by kazupon** [comment]
Hi!
Did you create your project with vue-cli?
`VUE APP_I18N_LOCALE` is env variables that it's set up with vue-cli-plugin-i18n.

**Comment by Stefjoe** [comment]
Hi,
yes! This is inside .env

```
VUE_APP_I18N_LOCALE=de
VUE_APP_I18N_FALLBACK_LOCALE=en
```
But i must said, that i changed LOCALE manually, first it was 

```
VUE_APP_I18N_LOCALE=en
VUE_APP_I18N_FALLBACK_LOCALE=en
```

Could this be the problem?

Rgds

**Comment by Stefjoe** [comment]
Ok, i think i fixed it, not clean, but it is working for me

I did this:

```
export default new VueI18n({
  locale: process.env.VUE_APP_I18N_LOCALE || 'de',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
  messages: loadLocaleMessages()
});
```

To this:

```
export default new VueI18n({
  locale:  'de',
  fallbackLocale:  'en',
  messages: loadLocaleMessages()
});
```

Maybe it helps someone :-)

**Comment by romiltrigyn** [comment]
Even on production build, I am getting _runtime-core.esm-bunEvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
_

**Comment by theromie** [comment]
When I deploy production build I am getting error in console of browser 
_runtime-core.esm-bundler.js:225 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"_

Vue: 3
Vue-i18n: ^9.1.0
`import { createI18n } from 'vue-i18n';
import en from "./locales/en.json";
import de from "./locales/de.json";

function loadLocaleMessages() {
  return {
    en: en,
    de: de
  };
}

export default createI18n({
  legacy: false,
  globalInjection: true,
  locale: process.env.VUE_APP_I18N_LOCALE || 'en',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'de',
  messages: loadLocaleMessages()
});
`


vue config
`pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'de',
      localeDir: 'locales',
      enableLegacy: false,
      runtimeOnly: false,
      compositionOnly: false,
      fullInstall: true
    }
  }`

**Comment by Yaojie1** [comment]
I had a similar problem

vendor.6e624922.js:1 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by Yaojie1** [comment]
Does anyone know how to solve this problem without changing the CSP

**Comment by darrinmn9** [comment]
@kazupon would you mind speaking to this csp issue with `unsafe-eval`. The core issue is similar to issues mentioned in the `next` repo with the usage of `new Function()`:
https://github.com/intlify/vue-i18n-next/issues/600
https://github.com/intlify/vue-i18n-next/issues/543
https://github.com/kazupon/vue-i18n/issues/1356

In your comment from those issues on v9, you mentioned the solution is documented here:
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only

Is there any solution for `vue-i18n v8` in a PROD csp environment that does not allow `unsafe-eval`? Thanks again for all your work!

**Comment by kazupon** [comment]
@darrinmn9 
H!
CSP issue does not occur in vue-i18n@v8.x
Do you have CSP issue in your project?
If you have it, please give us.

**Comment by darrinmn9** [comment]
Thanks for your quick reply!

My sincerest apologies for assuming the `unsafe-eval` issue was an issue with `vue-i18n v8`... I was a little misled by a few stack overflow posts and some previous comments on this thread about users getting the `unsafe-eval` csp issue. 😄 

After unminifying my code and looking for the exact line, it turns out the culprit was `webpack`. If others come by this similar issue and are also using `vue-cli`, these links will be helpful:

best solution:
https://github.com/webpack/webpack/issues/5627#issuecomment-394309966

usage with vue-cli:
https://stackoverflow.com/questions/64159951/vue-js-3-extension-breaks-while-using-vue-cli-service-build-due-to-unsafe-eval
