### ISSUE TITLE
How to use in module?

### ISSUE THREAD

**Issue by georgyfarniev** [kazupon/vue-i18n#670]
Hello. How vue-i18n can be used with modules? I have module built by vue-cli as library with externalized Vue instance (by default). How can I add vue-i18n localization INSIDE this module and prevent conflict?

**Comment by exoego** [comment]
Thanks for trying to use `vue-i18n` !!
Closing since this issue seems not satisfy requirement for issue list of this repo.
Please understand that "the issue list of this repo is **exclusively** for bug reports and feature requests", as stated in the issue template.

For simple questions, you may get answer from the following resources and user comunity:

>- Read the docs: https://github.com/kazupon/vue-i18n/blob/dev/README.md
>- Ask on the forums: http://forum.vuejs.org/
>- Look for/ask questions on stack overflow: https://stackoverflow.com/questions/ask?tags=vue-i18n
