### ISSUE TITLE
vue-i18n not working with link `https://cdn.jsdelivr.net/npm/vue-i18n`

### ISSUE THREAD

**Issue by jessicaWS** [kazupon/vue-i18n#678]
### Description
When loading production branch of vue-i18n
```
https://cdn.jsdelivr.net/npm/vue-i18n
```
the following error occurs
```
ReferenceError: module is not defined[Learn More] vue-i18n.common.js:1889
```
But when using the the following it does not
```
https://unpkg.com/vue-i18n/dist/vue-i18n.js
```

### Minimal example

```
<!DOCTYPE html>
<html lang="en">
	<meta charset="utf-8"/>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<script src="https://unpkg.com/vue"></script>
		<script src="https://cdn.jsdelivr.net/npm/vue-i18n"></script>
	</head>


	<body>
		<div id="app">
			<ol>
				<li v-for="todo in todos">
					{{ todo.text }}
				</li>
			</ol>
		</div>
		<script>

			Vue.use(VueI18n)

			const i18n = new VueI18n({
				locale: 'de',
				fallbackLocale : 'en',
				silentFallbackWarn: true,
				messages: {
				},
			});


			let app = new Vue({
				el : "#app",
				i18n,
				data : {todos: [
					{ text: 'Learn JavaScript' },
					{ text: 'Learn Vue' },
					{ text: 'Build something awesome' }
				]},
			})
		</script>
	</body>
</html>


```

### Browser
Firefox 60.8

**Comment by exoego** [comment]
It seems that https://cdn.jsdelivr.net/npm/vue-i18n is minified version by jsDelivr using Terser v3.14.1 accoding to header comment.

The file is not just minified, but also rewriten completely

* Some variables/functions, e.g. `numberFormatKeys` are exposed.
* Module systesm are used: `module.exports=VueI18n`, while original `dist/vue-i18n.js` have a polyfil for `module`.

Please refer the docs of jsDeliver, or find/ask help in other forums (e.g. StackOverflow), since the issue list is of this repository is dedicated for bug or feature request to `vue-i18n`.
Thanks for understanding.
