### ISSUE TITLE
$i18n.keyExists

### ISSUE THREAD

**Issue by Shinigami92** [kazupon/vue-i18n#681]
### Feature Request

`vuex-i18n` provides a function `keyExists`

Could this package also have this function so migration from/to `vuex-i18n`can be made easier?

Also I don't know if there is currently any way to identify if a locale does not exist.

Signature should be `$i18n.keyExists(key: string)`

**Comment by exoego** [comment]
I think this feature  already covered by `$te`

**Comment by Shinigami92** [comment]
Ah, thanks.
Maybe we could implement an **alias** that performs this function? This can be helpful if someone wants to migrate from vuex-i18n to this package.

Otherwise, you can close this request.

**Comment by exoego** [comment]
Closing since use case of `keyExists` is covered by `$te` or `i18n.te`.

@Shinigami92 
Thanks for understanding and suggesting *alias*es !!

I agree that having `alias` help users to migrate from other i18n tools.
It also increase readability even for existing users, since current names `t`, `tc`, `te`, or `d` are too short to convey intent.
I personally worry about adding `alias` increases complexity and size of `vue-i18n` a bit.
So it may be good to be implemented as extension to `vue-i18n` outside of this repository.

Don't hesitate to open a feature request regarding aliases, so we can gather feedbacks from other users !!
