### ISSUE TITLE
把一些公共的下拉框选项放到外部js文件，然后vue文件引进来的，现在问题是这样引进来以后，切换语言没有效果

### ISSUE THREAD

**Issue by shujiawei** [kazupon/vue-i18n#683]
### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by exoego** [comment]
Closing since this issue does not folow our issue template and [contributing guideline](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#pull-request-guidelines)
Also, please understand that English is used as a shared language in this repository.
Feel free to reopen when you updated the issue to satisfy these requirements.
