### ISSUE TITLE
Vue-i18n html:lang(en) condition

### ISSUE THREAD

**Issue by hiasince** [kazupon/vue-i18n#684]
First I use Vue-i18n 8.8.0 version.

It's not a bug. But I can't understand how It works.
I set font-family on css page like below.
```
/* Korean */
html:lang(ko) body {
    font-family: 'Noto Sans KR', -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji"
}

/* Japanese */
html:lang(ja) body {
    font-family: 'Noto Sans JP', sans-serif
}

/* Chinese */
html:lang(zh) body {
    font-family: 'Noto Sans SC', sans-serif
}
```

And then I just set locale (ja) property in VueI18n. And then css style became active.
![image](https://user-images.githubusercontent.com/24787741/62746579-663cec80-ba8b-11e9-9f28-d1f655aa6898.png)

I found that document.documentElement.lang value which is same as html.lang is empty.
I think VueI18n don't have any connection with html element. Why does it happen?

**Comment by exoego** [comment]
As of `v8.12.0`,  `vue-i18n` does not read/write `document.documentElement.lang`.
You may find it useful if you refer `setI18nLanguage` function example in https://kazupon.github.io/vue-i18n/guide/lazy-loading.html when you want to connect `vuei18n.locale` and `documentElement.lang`.

As stated in the issue template and [CONTRIBUTING.md](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), this issue list is dedicated for bug report/feature request.
I answered this question since it is trivial and I know it, but fore future questions, please consider to use ...
> - Ask on the forums: http://forum.vuejs.org/
> - Look for/ask questions on stack overflow: https://stackoverflow.com/questions/ask?tags=vue-i18n

I appreciate if you understand this

**Comment by hiasince** [comment]
@exoego 

Thanks for reply. 
I understand it. I will ask this Issue on forums.
