### ISSUE TITLE
组件插值里面的for属性是用来做什么的

### ISSUE THREAD

**Issue by zhangshilei0213** [kazupon/vue-i18n#686]
![image](https://user-images.githubusercontent.com/28614301/63081577-86cae200-bf76-11e9-9435-7f5eb6681dbb.png)
这个属性有什么作用，主要用于什么场景，为什么文档上没有描述

**Comment by exoego** [comment]
Closing since this issue does not folow our issue template and [contributing guideline](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#pull-request-guidelines)
Also, please understand that English is used as a shared language in this repository.
Feel free to reopen when you updated the issue to satisfy these requirements.
