### ISSUE TITLE
this.$t在data() 无法调用

### ISSUE THREAD

**Issue by 17721524631** [kazupon/vue-i18n#713]
![image](https://user-images.githubusercontent.com/35061684/64612202-ccf45380-d405-11e9-860c-4b1d4f9d3092.png)

**Comment by exoego** [comment]
Closing since this issue does not folow our issue template and [contributing guideline](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#pull-request-guidelines)
Also, please understand that English is used as a shared language in this repository.
Feel free to reopen when you updated the issue to satisfy these requirements.

**Comment by webrtcn** [comment]
data: () => ({
    title: this.$i18n.t('generate_random_choices'),
    choices: null,
    result: null
  }),
