### ISSUE TITLE
Linked translation fail

### ISSUE THREAD

**Issue by xucarry** [kazupon/vue-i18n#76]
I'm using vue2.0, my project init with vue-cli, when I used linked translation, an error occurred 'link.substr is not a function' 

local object
`{
def: {title: 'webpack app', link: '@:def.title'}
}`

template
`<div>{{ $t('def.title') }}</div><div>{{ $t('def.link') }}</div>`

I find The problem
vue-i18n.js@4.6.0  line 754:
`var matches = val.match(/(@:[\w|\.]+)/g);
        for (var idx in matches) {}`
matches is Array Object, and this object has a property '$remove' extend by vue

**Comment by kazupon** [comment]
sorry for my late reply. :bow:
I tried to reproduction from your feedback info.
http://jsfiddle.net/kazupon/1aLbzdzc/2/

However, I cannot reproduce this issue.
can you provide the minimum reporo code with jsfiddle or other please?

>matches is Array Object, and this object has a property '$remove' extend by due

I could understand about it.
That's fine with this plugin due to not use the $remove.

**Comment by kazupon** [comment]
close (inactivity)
