### ISSUE TITLE
i18n array and v-for

### ISSUE THREAD

**Issue by SamHH** [kazupon/vue-i18n#91]
Hope I'm not making a simple mistake here, but I can't seem to get i18n arrays to work within v-for loops?

### vue & vue-i18n version
2.0.7, 4.7.2

### Reproduction Link
http://jsfiddle.net/SamHH/chc7k4cz/

### What is Expected?

Iterate through the array.

### What is actually happening?

Console errors, e.g.: `Error when rendering root instance` & `Uncaught TypeError: n.replace is not a function`

**Comment by SamHH** [comment]
Maybe related to #59 ?

**Comment by kazupon** [comment]
Thank you for your feedback.
I'll try to fix.

**Comment by helloyxw** [comment]
this bug is fixed?  how to do can get array data?

**Comment by ConorMurphy21** [comment]
Is this issue fixed? when I try to translate an array it seems to fail. This is with version 9.*, vue 3, and options API.

Edit: need to use $tm instead of $t

**Comment by turgunov01** [comment]
"Hello! It appears I am facing a similar problem while attempting to define translations from json as an array using v-for in Nuxt3. However, instead of displaying the array content, I am seeing the variable itself portrayed as if it were a string manipulation, akin to the charAt function, which results in individual characters of the variable name being displayed.

What could be the solution of this error? ASAP

**Comment by ceigh** [comment]
It looks a bit complicated, what are `tm`, `rt`, I don't even understand what that means xD, where is my old good `$t()`, which was capable of such things?
